/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Blog model module.
 * @module model/Blog
 * @version 1.0.0
 */
class Blog {
    /**
     * Constructs a new <code>Blog</code>.
     * @alias module:model/Blog
     * @param _date {String} 
     * @param title {String} 
     * @param posttext {String} 
     * @param image {String} 
     * @param viewpost {String} 
     */
    constructor(_date, title, posttext, image, viewpost) { 
        
        Blog.initialize(this, _date, title, posttext, image, viewpost);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _date, title, posttext, image, viewpost) { 
        obj['date'] = _date;
        obj['title'] = title;
        obj['posttext'] = posttext;
        obj['image'] = image;
        obj['viewpost'] = viewpost;
    }

    /**
     * Constructs a <code>Blog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Blog} obj Optional instance to populate.
     * @return {module:model/Blog} The populated <code>Blog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Blog();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('posttext')) {
                obj['posttext'] = ApiClient.convertToType(data['posttext'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('viewpost')) {
                obj['viewpost'] = ApiClient.convertToType(data['viewpost'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Blog.prototype['_id'] = undefined;

/**
 * @member {String} date
 */
Blog.prototype['date'] = undefined;

/**
 * @member {String} title
 */
Blog.prototype['title'] = undefined;

/**
 * @member {String} posttext
 */
Blog.prototype['posttext'] = undefined;

/**
 * @member {String} image
 */
Blog.prototype['image'] = undefined;

/**
 * @member {String} viewpost
 */
Blog.prototype['viewpost'] = undefined;






export default Blog;

